# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
fr:
  languageCode: fr
  languageName: Français
  contentDir: content/fr
  weight: 1


en:
  languageCode: en-us
  langugaeName: English
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
